# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Free Trial(9a43f889-f40c-4ce5-a9d5-8bceedf4ce26)'
        azureContainerRegistry: '{"loginServer":"devcontainerregis.azurecr.io", "id" : "/subscriptions/9a43f889-f40c-4ce5-a9d5-8bceedf4ce26/resourceGroups/dev-container-resc/providers/Microsoft.ContainerRegistry/registries/devcontainerregis"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'